
title: Notes
description: >- 
  Blog-style academic notes with math support and concept linking.
baseurl: "/notes"
url: "https://jhpaeng306.github.io"

theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

mathjax: true

just_the_docs:
  collections:
    math:
      output: true
      permalink: /:collection/:path/
  search_enabled: true
  nav_sort: case_insensitive
