title: Notes
description: Jinhee Paeng's academic blog
baseurl: "/notes-blog"
url: "https://jhpaeng306.github.io"

theme: just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

mathjax: true

collections:
  topics:
    output: true
    permalink: /topics/:path/

just_the_docs:
  collections:
    topics:
      output: true
      permalink: /topics/:path/
  search_enabled: true
  nav_sort: case_insensitive
  toc:
    min_level: 2
    max_level: 3
