
title: Notes
description: Jinhee Paeng's academic blog on applied math, neuroscience, and AI.
baseurl: "/notes"
url: "https://jhpaeng306.github.io"
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

mathjax: true

just_the_docs:
  collections:
    math:
      output: true
      permalink: /:collection/:path/
  search_enabled: true
  nav_sort: case_insensitive
